# Detecting Air Pressure System Failure in Trucks

## 01 - Data Understanding

The goal of this project is to predict whether the Air Pressure System (APS)
of a truck will fail or not.

In this notebook, we will understand the dataset before building machine
learning models.

## 1. Import Libraries

We use pandas and numpy to work with the dataset.

In [2]:
import pandas as pd
import numpy as np

## 2. Load the Training and Test Datasets

The APS dataset contains some information before the actual table.
Therefore, we skip the first 20 rows.

The value `na` represents a missing value.

In [3]:
train_df=pd.read_csv("../data/raw/aps_failure_training_set.csv",skiprows=20, na_values="na")

test_df=pd.read_csv("../data/raw/aps_failure_test_set.csv",skiprows=20, na_values="na")

## 3. Check Dataset Size

First, let's check how many rows and columns are present in both datasets.

In [4]:
print("Training data:", train_df.shape)
print("Test data:", test_df.shape)

Training data: (60000, 171)
Test data: (16000, 171)

## 4. Look at the First 5 Rows

Let's see what the actual data looks like.

In [6]:
train_df.head()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,NaN,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,NaN,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,0.0,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,NaN,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0

## Look at the Last 5 Rows

In [30]:
train_df.tail()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
59995,neg,153002,NaN,6.640000e+02,186.0,0.0,0.0,0.0,0.0,0.0,...,998500.0,566884.0,1290398.0,1218244.0,1019768.0,717762.0,898642.0,28588.0,0.0,0.0
59996,neg,2286,NaN,2.130707e+09,224.0,0.0,0.0,0.0,0.0,0.0,...,10578.0,6760.0,21126.0,68424.0,136.0,0.0,0.0,0.0,0.0,0.0
59997,neg,112,0.0,2.130706e+09,18.0,0.0,0.0,0.0,0.0,0.0,...,792.0,386.0,452.0,144.0,146.0,2622.0,0.0,0.0,0.0,0.0
59998,neg,80292,NaN,2.130706e+09,494.0,0.0,0.0,0.0,0.0,0.0,...,699352.0,222654.0,347378.0,225724.0,194440.0,165070.0,802280.0,388422.0,0.0,0.0
59999,neg,40222,NaN,6.980000e+02,628.0,0.0,0.0,0.0,0.0,0.0,...,440066.0,183200.0,344546.0,254068.0,225148.0,158304.0,170384.0,158.0,0.0,0.0

## Look at the Random 5 Rows

In [31]:
train_df.sample(5)

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
25171,neg,3094,NaN,6.200000e+01,56.0,0.0,0.0,0.0,0.0,50.0,...,28458.0,9588.0,23108.0,49968.0,21162.0,7640.0,112.0,0.0,0.0,0.0
41580,neg,396,NaN,2.130706e+09,24.0,0.0,0.0,0.0,0.0,0.0,...,2650.0,1102.0,18888.0,1502.0,2148.0,6908.0,370.0,0.0,0.0,0.0
29784,neg,28454,NaN,2.130706e+09,1900.0,0.0,0.0,0.0,0.0,0.0,...,421568.0,255536.0,223372.0,22000.0,2756.0,84.0,18.0,0.0,0.0,0.0
159,neg,1304,2.0,2.130706e+09,116.0,0.0,0.0,0.0,0.0,0.0,...,8220.0,4720.0,10342.0,8320.0,8380.0,17468.0,268.0,0.0,0.0,0.0
4780,neg,8,2.0,4.000000e+00,4.0,0.0,0.0,0.0,0.0,0.0,...,54.0,14.0,46.0,64.0,12.0,0.0,0.0,0.0,0.0,0.0

## 5. Check Column Names

Let's see all the columns in the dataset.

In [7]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='str', length=171)

In [8]:
print("Number of columns:", len(train_df.columns))

Number of columns: 171

## 6. Understand the Target Variable

The target column is `class`.

It has two values:

- `neg` → No APS failure
- `pos` → APS failure

In [11]:
train_df["class"].unique()

<StringArray>
['neg', 'pos']
Length: 2, dtype: str

## 7. Check Class Distribution

Let's check how many trucks belong to each class.

In [ ]:
train_df["class"].value_counts()

# dataset is highly imbalanced.

class
neg    59000
pos     1000
Name: count, dtype: int64

In [14]:
train_df["class"].value_counts(normalize=True)*100  #calculate percentages:

class
neg    98.333333
pos     1.666667
Name: proportion, dtype: float64

## 8. Check Missing Values

The APS dataset contains many missing values.

Let's find out how many missing values each column has.

In [22]:
train_df.isnull().sum().head(20)

class         0
aa_000        0
ab_000    46329
ac_000     3335
ad_000    14861
ae_000     2500
af_000     2500
ag_000      671
ag_001      671
ag_002      671
ag_003      671
ag_004      671
ag_005      671
ag_006      671
ag_007      671
ag_008      671
ag_009      671
ah_000      645
ai_000      629
aj_000      629
dtype: int64

## 9. Missing Value Percentage

We calculate the percentage of missing values in each column.

In [23]:
missing_percentage = train_df.isnull().mean() * 100

missing_percentage.sort_values(ascending=False).head(10)

br_000    82.106667
bq_000    81.203333
bp_000    79.566667
bo_000    77.221667
ab_000    77.215000
cr_000    77.215000
bn_000    73.348333
bm_000    65.915000
bl_000    45.461667
bk_000    38.390000
dtype: float64

## 10. Check Data Types

Let's check whether the columns contain integer, float, or other types of data.

In [24]:
train_df.dtypes.value_counts()

float64    169
str          1
int64        1
Name: count, dtype: int64

In [25]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 171 entries, class to eg_000
dtypes: float64(169), int64(1), str(1)
memory usage: 78.3 MB

## 11. Check Duplicate Rows

Let's check whether the dataset contains duplicate records.

In [26]:
train_df.duplicated().sum()

np.int64(0)

## 12. Basic Statistical Summary

Let's look at the basic statistics of the numerical columns.

In [27]:
train_df.describe()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
count,6.000000e+04,13671.000000,5.666500e+04,4.513900e+04,57500.000000,57500.000000,5.932900e+04,5.932900e+04,5.932900e+04,5.932900e+04,...,5.932900e+04,5.932900e+04,5.932900e+04,5.932900e+04,5.932900e+04,5.932900e+04,5.932900e+04,5.932900e+04,57276.000000,57277.000000
mean,5.933650e+04,0.713189,3.560143e+08,1.906206e+05,6.819130,11.006817,2.216364e+02,9.757223e+02,8.606015e+03,8.859128e+04,...,4.454897e+05,2.111264e+05,4.457343e+05,3.939462e+05,3.330582e+05,3.462714e+05,1.387300e+05,8.388915e+03,0.090579,0.212756
std,1.454301e+05,3.478962,7.948749e+08,4.040441e+07,161.543373,209.792592,2.047846e+04,3.420053e+04,1.503220e+05,7.617312e+05,...,1.155540e+06,5.433188e+05,1.168314e+06,1.121044e+06,1.069160e+06,1.728056e+06,4.495100e+05,4.747043e+04,4.368855,8.830641
min,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,8.340000e+02,0.000000,1.600000e+01,2.400000e+01,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.936000e+03,1.166000e+03,2.700000e+03,3.584000e+03,5.120000e+02,1.100000e+02,0.000000e+00,0.000000e+00,0.000000,0.000000
50%,3.077600e+04,0.000000,1.520000e+02,1.260000e+02,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.337960e+05,1.120860e+05,2.215180e+05,1.899880e+05,9.243200e+04,4.109800e+04,3.812000e+03,0.000000e+00,0.000000,0.000000
75%,4.866800e+04,0.000000,9.640000e+02,4.300000e+02,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,4.383960e+05,2.182320e+05,4.666140e+05,4.032220e+05,2.750940e+05,1.678140e+05,1.397240e+05,2.028000e+03,0.000000,0.000000
max,2.746564e+06,204.000000,2.130707e+09,8.584298e+09,21050.000000,20070.000000,3.376892e+06,4.109372e+06,1.055286e+07,6.340207e+07,...,7.793393e+07,3.775839e+07,9.715238e+07,5.743524e+07,3.160781e+07,1.195801e+08,1.926740e+07,3.810078e+06,482.000000,1146.000000

## 13. Separate Features and Target

The `class` column is our target.

All other columns are input features.

In [ ]:
x = train_df.drop(columns=["class"])

y = train_df["class"]

"""
X → features
y → target
"""

In [29]:
print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: (60000, 170)
y shape: (60000,)