# Detecting Air Pressure System Failure in Trucks

## 01 - Data Understanding

The goal of this project is to predict whether the Air Pressure System (APS)
of a truck will fail or not.

In this notebook, we will understand the dataset before building machine
learning models.

##### 1. Import Libraries

We use pandas and numpy to work with the dataset.

In [7]:
import pandas as pd
import numpy as np

##### 2. Load the Training and Test Datasets

The APS dataset contains some information before the actual table.
Therefore, we skip the first 20 rows.

The value `na` represents a missing value.

In [2]:
train_df=pd.read_csv("../data/raw/aps_failure_training_set.csv",skiprows=20, na_values="na")

test_df=pd.read_csv("../data/raw/aps_failure_test_set.csv",skiprows=20, na_values="na")

In [3]:
train_df.head()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,NaN,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,NaN,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,0.0,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,NaN,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0

In [4]:
test_df.head()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,60,0.0,20.0,12.0,0.0,0.0,0.0,0.0,0.0,...,1098.0,138.0,412.0,654.0,78.0,88.0,0.0,0.0,0.0,0.0
1,neg,82,0.0,68.0,40.0,0.0,0.0,0.0,0.0,0.0,...,1068.0,276.0,1620.0,116.0,86.0,462.0,0.0,0.0,0.0,0.0
2,neg,66002,2.0,212.0,112.0,0.0,0.0,0.0,0.0,0.0,...,495076.0,380368.0,440134.0,269556.0,1315022.0,153680.0,516.0,0.0,0.0,0.0
3,neg,59816,NaN,1010.0,936.0,0.0,0.0,0.0,0.0,0.0,...,540820.0,243270.0,483302.0,485332.0,431376.0,210074.0,281662.0,3232.0,0.0,0.0
4,neg,1814,NaN,156.0,140.0,0.0,0.0,0.0,0.0,0.0,...,7646.0,4144.0,18466.0,49782.0,3176.0,482.0,76.0,0.0,0.0,0.0

##### Check training dataset shape

In [5]:
train_df.shape

(60000, 171)

##### Check test dataset shape

In [6]:
test_df.shape

(16000, 171)

##### Check column name

In [8]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='str', length=171)

In [9]:
len(train_df.columns)

171

##### Check data information

In [10]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 171 entries, class to eg_000
dtypes: float64(169), int64(1), str(1)
memory usage: 78.3 MB

##### Check data types

In [12]:
train_df.dtypes.value_counts()

float64    169
str          1
int64        1
Name: count, dtype: int64

##### Check target values

In [ ]:
train_df["class"].unique()  #two classes: "neg" and "pos"

#Binary Classification Problem

<StringArray>
['neg', 'pos']
Length: 2, dtype: str

##### Check target count

In [14]:
train_df["class"].value_counts()

class
neg    59000
pos     1000
Name: count, dtype: int64

##### Check target percentage

In [16]:
train_df["class"].value_counts(normalize=True)*100

class
neg    98.333333
pos     1.666667
Name: proportion, dtype: float64

##### Check missing values

In [17]:
train_df.isnull().sum()

class         0
aa_000        0
ab_000    46329
ac_000     3335
ad_000    14861
          ...
ee_007      671
ee_008      671
ee_009      671
ef_000     2724
eg_000     2723
Length: 171, dtype: int64

##### Check total missing values

In [18]:
train_df.isnull().sum().sum()

np.int64(850015)

##### Check duplicate rows

In [19]:
train_df.duplicated().sum()

np.int64(0)