##### import libraries

In [9]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from imblearn.over_sampling import SMOTE

##### Load training data

In [2]:
train_df = pd.read_csv(
    "../data/raw/aps_failure_training_set.csv",
    skiprows=20,
    na_values="na"
)

In [3]:
train_df.head()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,NaN,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,NaN,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,0.0,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,NaN,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0

##### Load test data

In [4]:
test_df = pd.read_csv(
    "../data/raw/aps_failure_test_set.csv",
    skiprows=20,
    na_values="na"
)

In [5]:
test_df.head()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,60,0.0,20.0,12.0,0.0,0.0,0.0,0.0,0.0,...,1098.0,138.0,412.0,654.0,78.0,88.0,0.0,0.0,0.0,0.0
1,neg,82,0.0,68.0,40.0,0.0,0.0,0.0,0.0,0.0,...,1068.0,276.0,1620.0,116.0,86.0,462.0,0.0,0.0,0.0,0.0
2,neg,66002,2.0,212.0,112.0,0.0,0.0,0.0,0.0,0.0,...,495076.0,380368.0,440134.0,269556.0,1315022.0,153680.0,516.0,0.0,0.0,0.0
3,neg,59816,NaN,1010.0,936.0,0.0,0.0,0.0,0.0,0.0,...,540820.0,243270.0,483302.0,485332.0,431376.0,210074.0,281662.0,3232.0,0.0,0.0
4,neg,1814,NaN,156.0,140.0,0.0,0.0,0.0,0.0,0.0,...,7646.0,4144.0,18466.0,49782.0,3176.0,482.0,76.0,0.0,0.0,0.0

##### Check Shapes

In [7]:
print("Training Data :",train_df.shape)
print("Test Data :",test_df.shape)

Training Data : (60000, 171)
Test Data : (16000, 171)

##### Separate Features and Target

In [8]:
X=train_df.drop(columns=["class"])
y=train_df["class"]

##### Label Encoder

In [10]:
le=LabelEncoder()

In [11]:
y=le.fit_transform(y)

In [ ]:
print(le.classes_)

"""
neg = 0
pos = 1
"""

['neg' 'pos']

In [13]:
pd.Series(y).value_counts()

0    59000
1     1000
Name: count, dtype: int64

##### Train/test Split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [18]:
x_train.shape

(48000, 170)

In [19]:
x_test.shape

(12000, 170)

In [20]:
y_train.shape

(48000,)

In [21]:
y_test.shape

(12000,)

##### Check Class Distribution

In [23]:
pd.Series(y_train).value_counts()

0    47200
1      800
Name: count, dtype: int64

In [22]:
pd.Series(y_test).value_counts()

0    11800
1      200
Name: count, dtype: int64

##### Handle Missing Values->SimpleImputer->Mean

In [24]:
si=SimpleImputer(strategy="mean")

In [25]:
x_train=si.fit_transform(x_train)

In [26]:
x_test=si.transform(x_test)