##### import libraries

In [86]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from imblearn.over_sampling import SMOTE

##### Load training data

In [87]:
train_df = pd.read_csv(
    "../data/raw/aps_failure_training_set.csv",
    skiprows=20,
    na_values="na"
)

In [88]:
train_df.head()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,76698,NaN,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,NaN,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,0.0,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,NaN,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0

##### Load test data

In [89]:
test_df = pd.read_csv(
    "../data/raw/aps_failure_test_set.csv",
    skiprows=20,
    na_values="na"
)

In [90]:
test_df.head()

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,60,0.0,20.0,12.0,0.0,0.0,0.0,0.0,0.0,...,1098.0,138.0,412.0,654.0,78.0,88.0,0.0,0.0,0.0,0.0
1,neg,82,0.0,68.0,40.0,0.0,0.0,0.0,0.0,0.0,...,1068.0,276.0,1620.0,116.0,86.0,462.0,0.0,0.0,0.0,0.0
2,neg,66002,2.0,212.0,112.0,0.0,0.0,0.0,0.0,0.0,...,495076.0,380368.0,440134.0,269556.0,1315022.0,153680.0,516.0,0.0,0.0,0.0
3,neg,59816,NaN,1010.0,936.0,0.0,0.0,0.0,0.0,0.0,...,540820.0,243270.0,483302.0,485332.0,431376.0,210074.0,281662.0,3232.0,0.0,0.0
4,neg,1814,NaN,156.0,140.0,0.0,0.0,0.0,0.0,0.0,...,7646.0,4144.0,18466.0,49782.0,3176.0,482.0,76.0,0.0,0.0,0.0

##### Check Shapes

In [91]:
print("Training Data :",train_df.shape)
print("Test Data :",test_df.shape)

Training Data : (60000, 171)
Test Data : (16000, 171)

##### Combine training and test data

In [92]:
df=pd.concat([train_df,test_df],ignore_index=True)

In [93]:
df.shape

(76000, 171)

##### Create preprocessing copy

In [95]:
df_preprocessed= df.copy()

##### Check missing values

In [96]:
df_preprocessed.isnull().sum()

class         0
aa_000        0
ab_000    58692
ac_000     4261
ad_000    18842
          ...
ee_007      863
ee_008      863
ee_009      863
ef_000     3486
eg_000     3485
Length: 171, dtype: int64

In [97]:
df_preprocessed.isnull().sum().sum()

np.int64(1078695)

##### Check duplicates

In [98]:
df_preprocessed.duplicated().sum()

np.int64(0)

##### Separate x and y

In [99]:
x=df_preprocessed.drop(columns=['class'])
y=df_preprocessed['class']

In [101]:
x.shape,y.shape

((76000, 170), (76000,))

##### Label Encoding

In [102]:
le=LabelEncoder()

In [103]:
y=le.fit_transform(y)

In [104]:
le.classes_

array(['neg', 'pos'], dtype=object)

In [ ]:
""""
neg → 0
pos → 1
"""

##### Check Class distribution

In [105]:
pd.Series(y).value_counts()

0    74625
1     1375
Name: count, dtype: int64

##### Train/Test Split

In [106]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [107]:
x_train.shape

(60800, 170)

In [108]:
x_test.shape

(15200, 170)

In [109]:
y_train.shape

(60800,)

In [110]:
y_test.shape

(15200,)

In [111]:
x_train.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
1061,580,NaN,2.400000e+01,24.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3804.0,1236.0,2250.0,2312.0,3192.0,10986.0,0.0,0.0,0.0,0.0
23655,181460,NaN,7.634000e+03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75602,776,NaN,2.130706e+09,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2058.0,1974.0,12616.0,16582.0,2036.0,32.0,22.0,0.0,0.0,0.0
33058,51612,0.0,3.720000e+02,336.0,0.0,0.0,0.0,0.0,0.0,12020.0,...,331566.0,149950.0,248738.0,396622.0,1047050.0,84630.0,2388.0,0.0,0.0,0.0
67235,1530,NaN,9.800000e+01,88.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7284.0,4290.0,13262.0,45510.0,786.0,14.0,0.0,0.0,0.0,0.0

In [112]:
x_test.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
58199,32076,NaN,2.130706e+09,1346.0,0.0,0.0,26.0,12.0,12.0,76.0,...,223976.0,96228.0,162960.0,111120.0,106168.0,93890.0,427716.0,69528.0,0.0,0.0
48714,8,NaN,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.0,14.0,106.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42680,1274,0.0,2.130706e+09,32.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4634.0,2472.0,9102.0,15180.0,17622.0,6444.0,480.0,34.0,0.0,0.0
5761,276110,0.0,4.840000e+02,0.0,256.0,982.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
62322,5010,NaN,2.130706e+09,84.0,0.0,0.0,0.0,0.0,0.0,0.0,...,47138.0,22674.0,45764.0,33572.0,26262.0,25218.0,23446.0,1456.0,0.0,0.0

##### Check class distribution

In [113]:
print("Training data:")
print(pd.Series(y_train).value_counts())

print("\nTesting data:")
print(pd.Series(y_test).value_counts())

Training data:
0    59700
1     1100
Name: count, dtype: int64

Testing data:
0    14925
1      275
Name: count, dtype: int64

##### Mean Imputation

In [114]:
si = SimpleImputer(strategy="mean")

In [115]:
x_train_imp=si.fit_transform(x_train)

In [116]:
x_test_imp=si.transform(x_test)

##### Convert back to DataFrame

In [118]:
x_train_imp=pd.DataFrame(x_train_imp,columns=x_train.columns,index=x_train.index)

In [119]:
x_train_imp.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
1061,580.0,0.727154,2.400000e+01,24.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3804.0,1236.0,2250.0,2312.0,3192.0,10986.0,0.0,0.0,0.0,0.0
23655,181460.0,0.727154,7.634000e+03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75602,776.0,0.727154,2.130706e+09,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2058.0,1974.0,12616.0,16582.0,2036.0,32.0,22.0,0.0,0.0,0.0
33058,51612.0,0.000000,3.720000e+02,336.0,0.0,0.0,0.0,0.0,0.0,12020.0,...,331566.0,149950.0,248738.0,396622.0,1047050.0,84630.0,2388.0,0.0,0.0,0.0
67235,1530.0,0.727154,9.800000e+01,88.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7284.0,4290.0,13262.0,45510.0,786.0,14.0,0.0,0.0,0.0,0.0

In [120]:
x_test_imp=pd.DataFrame(x_test_imp,columns=x_test.columns,index=x_test.index)

In [121]:
x_test_imp.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
58199,32076.0,0.727154,2.130706e+09,1346.0,0.0,0.0,26.000000,12.000000,12.000000,76.00000,...,223976.00000,96228.000000,162960.000000,111120.000000,106168.000000,93890.000000,427716.000000,69528.000000,0.0,0.0
48714,8.0,0.727154,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,...,34.00000,14.000000,106.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
42680,1274.0,0.000000,2.130706e+09,32.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,...,4634.00000,2472.000000,9102.000000,15180.000000,17622.000000,6444.000000,480.000000,34.000000,0.0,0.0
5761,276110.0,0.000000,4.840000e+02,0.0,256.0,982.0,232.852255,1254.750033,9793.050412,92768.11938,...,448748.69286,213013.120116,450854.057564,398906.972498,336443.509361,345093.382262,139780.348342,8413.701806,0.0,0.0
62322,5010.0,0.727154,2.130706e+09,84.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,...,47138.00000,22674.000000,45764.000000,33572.000000,26262.000000,25218.000000,23446.000000,1456.000000,0.0,0.0

##### Check missing values

In [122]:
x_train_imp.isnull().sum().sum()

np.int64(0)

In [123]:
x_test_imp.isnull().sum().sum()

np.int64(0)

##### Save imputer

In [124]:
import pickle

In [126]:
with open("../artifacts/imputer.pkl", "wb") as file:
    pickle.dump(si, file)

##### StandardScaler

In [127]:
scaler=StandardScaler()

In [128]:
x_train_scaled=scaler.fit_transform(x_train_imp)

In [129]:
x_test_scaled = scaler.transform(x_test_imp)

##### Convert scaled data to DataFrame

In [130]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns,index=x_train.index)

In [131]:
x_test_scaled=pd.DataFrame(x_test_scaled,columns=x_test.columns,index=x_test.index)

In [132]:
x_train_scaled.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
1061,-0.211517,-6.672382e-17,-0.461639,-0.005405,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.376808,-0.380645,-0.370954,-0.345227,-0.303347,-0.194706,-0.294093,-0.169739,-0.021052,-0.021654
23655,0.418794,-6.672382e-17,-0.461629,-0.005406,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.380030,-0.382866,-0.372814,-0.347240,-0.306253,-0.201108,-0.294093,-0.169739,-0.021052,-0.021654
75602,-0.210834,-6.672382e-17,2.293749,-0.005406,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.378287,-0.379318,-0.362382,-0.332806,-0.304399,-0.201089,-0.294047,-0.169739,-0.021052,-0.021654
33058,-0.033686,-4.370160e-01,-0.461639,-0.005396,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.096702,...,-0.099238,-0.113349,-0.167131,-0.001989,0.646840,-0.151789,-0.289069,-0.169739,-0.021052,-0.021654
67235,-0.208206,-6.672382e-17,-0.461639,-0.005404,-0.042858,-0.053164,-0.01138,-0.022936,-0.055919,-0.111097,...,-0.373861,-0.375156,-0.361848,-0.307624,-0.305537,-0.201100,-0.294093,-0.169739,-0.021052,-0.021654

In [133]:
x_test_scaled.head()

,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
58199,-0.101763,-6.672382e-17,2.293749,-0.005367,-0.042858,-0.053164,-1.010922e-02,-0.022717,-5.585031e-02,-0.111006,...,-1.903521e-01,-0.209908,-2.380616e-01,-2.505123e-01,-0.209612,-0.146392,6.058065e-01,1.232924,-0.021052,-0.021654
48714,-0.213510,-6.672382e-17,-0.461639,-0.005406,-0.042858,-0.053164,-1.137989e-02,-0.022936,-5.591883e-02,-0.111097,...,-3.800007e-01,-0.382841,-3.727268e-01,-3.472398e-01,-0.306253,-0.201108,-2.940930e-01,-0.169739,-0.021052,-0.021654
42680,-0.209098,-4.370160e-01,2.293749,-0.005405,-0.042858,-0.053164,-1.137989e-02,-0.022936,-5.591883e-02,-0.111097,...,-3.761052e-01,-0.378423,-3.652879e-01,-3.340260e-01,-0.290212,-0.197353,-2.930830e-01,-0.169053,-0.021052,-0.021654
5761,0.748620,-4.370160e-01,-0.461639,-0.005406,1.516210,4.596903,-1.389017e-18,0.000000,-1.038652e-17,0.000000,...,4.929403e-17,0.000000,-4.813233e-17,5.066850e-17,0.000000,0.000000,-6.123344e-17,0.000000,-0.021052,-0.021654
62322,-0.196079,-6.672382e-17,2.293749,-0.005404,-0.042858,-0.053164,-1.137989e-02,-0.022936,-5.591883e-02,-0.111097,...,-3.401100e-01,-0.342113,-3.349718e-01,-3.180161e-01,-0.282347,-0.186412,-2.447634e-01,-0.140365,-0.021052,-0.021654

##### Save Scaler

In [134]:
with open("../artifacts/scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)